ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LOGIN';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SUSPICIOUS_LOGIN';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PASSWORD_CHANGED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TRANSACTION_ALERT';
