const ORDER_STATUS = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  PAID: "PAID",
  PROCESSING: "PROCESSING",
  READY_FOR_DELIVERY: "READY_FOR_DELIVERY",
  IN_DELIVERY: "IN_DELIVERY",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
};

const ORDER_LIFECYCLE_STATUSES = Object.values(ORDER_STATUS);

const VALID_STATUS_TRANSITIONS = {
  [ORDER_STATUS.PENDING_PAYMENT]: [ORDER_STATUS.PAID, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PAID]: [ORDER_STATUS.PROCESSING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PROCESSING]: [ORDER_STATUS.READY_FOR_DELIVERY, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.READY_FOR_DELIVERY]: [ORDER_STATUS.IN_DELIVERY, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.IN_DELIVERY]: [ORDER_STATUS.DELIVERED],
  [ORDER_STATUS.DELIVERED]: [],
  [ORDER_STATUS.CANCELLED]: [],
};

function isValidOrderStatusTransition(currentStatus, nextStatus) {
  return (VALID_STATUS_TRANSITIONS[currentStatus] || []).includes(nextStatus);
}

function isReadyForDelivery(status) {
  return status === ORDER_STATUS.READY_FOR_DELIVERY;
}

module.exports = {
  ORDER_STATUS,
  ORDER_LIFECYCLE_STATUSES,
  VALID_STATUS_TRANSITIONS,
  isValidOrderStatusTransition,
  isReadyForDelivery,
};
